### ISSUE TITLE
[Question] Jar on Maven Central?

### ISSUE THREAD

**Issue by JeanRouillier** [phrase/phrase-java#11]
Hello Phrase team,

My company is currently using your nice Translation tool and I had a quick question.
As you provide theses sources, why not uploading JAR on maven central so everyone can easily use it.
Instead of having to download sources on my own and pushing on a private registry. 

I think you may have your reasons but wanted to understand it.

Best Regards.

**Comment by jablan** [comment]
hey @JeanRouillier this was long on our TODO list and finally we got to implement it. Setting up publishing to maven central is far from trivial, and everyone has their own way of doing it, but we managed eventually, after some back and forth. Hopefully it works well for you now.
