### ISSUE TITLE
[Question] v2.2.0+ on Maven Central 

### ISSUE THREAD

**Issue by IShmelov** [phrase/phrase-java#12]
Hi Guys,
The newest release on GitHub is 2.5.0, but the latest version on Maven Central is 2.2.0:
https://repo.maven.apache.org/maven2/com/phrase/phrase-java/

Don't you have any plans or schedules for when the latest version will be available on Maven Central?

Regards,

**Comment by jablan** [comment]
Hi @IShmelov our maven central access was broken for a while, but it should be fixed now, soon we plan to release a new version of all clients and Java will hopefully be there. I'll leave this issue open until then.

**Comment by jablan** [comment]
hey @IShmelov version 2.6 is pushed to Maven Central https://central.sonatype.com/artifact/com.phrase/phrase-java/versions
